version: 1

update_configs:
  - package_manager: 'javascript'
    default_reviewers:
      - 'quentinxhu'
    directory: '/'
    target_branch: 'master'
    update_schedule: 'live'
    allowed_updates:
      - match:
          update_type: 'security'
